/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package APP;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author VIVEK
 */
public class NewCustomer extends javax.swing.JFrame {
   
    public int flag=0;
   
    public double netamount=0,discount=0,totalamount=0;
    DecimalFormat df = new DecimalFormat(" #.###");
    /**
     * Creates new form NewCustomer//
     */
    public NewCustomer() {
        initComponents();
        showdatetime();
        showData();
//        Date dateAndTime = Calendar.getInstance().getTime();
//                 //(dateAndTime.toString());
//          jLabel16.setText(dateAndTime.toString());

     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbladdnewcustomer = new javax.swing.JLabel();
        lblcustomerdetail = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblPhoneNo = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        tfPhoneNo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAddress = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        tfSearch = new javax.swing.JTextField();
        lblEnterItemName = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblData1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tfSearch1 = new javax.swing.JTextField();
        lblEnterItemName1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lblExtraItem = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        lblTotalAmount = new javax.swing.JLabel();
        lblAMount = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfdiscount = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblAMount1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Customer");
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        lbladdnewcustomer.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lbladdnewcustomer.setForeground(new java.awt.Color(102, 0, 0));
        lbladdnewcustomer.setText("        INVOICE");
        lbladdnewcustomer.setAlignmentY(0.0F);

        lblcustomerdetail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblcustomerdetail.setText("CUSTOMER  DETAILS:");

        lblName.setText("Name : ");

        lblPhoneNo.setText("Phone No :");

        lblAddress.setText("Address :");

        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });

        tfPhoneNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPhoneNoActionPerformed(evt);
            }
        });
        tfPhoneNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPhoneNoKeyReleased(evt);
            }
        });

        taAddress.setColumns(20);
        taAddress.setRows(5);
        jScrollPane1.setViewportView(taAddress);

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "                                 Item Name", "      Price per Unit", "     GST %", "      Price including GST"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblData.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tblData.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tblData);
        if (tblData.getColumnModel().getColumnCount() > 0) {
            tblData.getColumnModel().getColumn(0).setResizable(false);
            tblData.getColumnModel().getColumn(0).setPreferredWidth(330);
            tblData.getColumnModel().getColumn(1).setResizable(false);
            tblData.getColumnModel().getColumn(1).setPreferredWidth(120);
            tblData.getColumnModel().getColumn(2).setResizable(false);
            tblData.getColumnModel().getColumn(2).setPreferredWidth(70);
            tblData.getColumnModel().getColumn(3).setResizable(false);
            tblData.getColumnModel().getColumn(3).setPreferredWidth(150);
        }

        tfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearchActionPerformed(evt);
            }
        });
        tfSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfSearchKeyReleased(evt);
            }
        });

        lblEnterItemName.setText("Search Item Name ");

        tblData1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "  S.No :", "                   Item Name", "  Price per Unit", " Quantity", "  Total Price", "  GST %", "  Price including GST"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblData1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tblData1.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tblData1);
        if (tblData1.getColumnModel().getColumnCount() > 0) {
            tblData1.getColumnModel().getColumn(0).setResizable(false);
            tblData1.getColumnModel().getColumn(0).setPreferredWidth(60);
            tblData1.getColumnModel().getColumn(1).setResizable(false);
            tblData1.getColumnModel().getColumn(1).setPreferredWidth(330);
            tblData1.getColumnModel().getColumn(2).setResizable(false);
            tblData1.getColumnModel().getColumn(2).setPreferredWidth(120);
            tblData1.getColumnModel().getColumn(3).setResizable(false);
            tblData1.getColumnModel().getColumn(3).setPreferredWidth(70);
            tblData1.getColumnModel().getColumn(4).setResizable(false);
            tblData1.getColumnModel().getColumn(4).setPreferredWidth(150);
            tblData1.getColumnModel().getColumn(5).setResizable(false);
            tblData1.getColumnModel().getColumn(5).setPreferredWidth(80);
            tblData1.getColumnModel().getColumn(6).setResizable(false);
            tblData1.getColumnModel().getColumn(6).setPreferredWidth(170);
        }

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jLabel1.setText(" Quantity: ");

        jButton1.setText("ADD Item");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tfSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearch1ActionPerformed(evt);
            }
        });

        lblEnterItemName1.setText(" Item Name ");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });

        jLabel2.setText(" Quantity: ");

        jButton2.setText("ADD Item");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblExtraItem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblExtraItem.setText("Extra Items :  ");

        jLabel3.setText("Price per Unit");

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });

        jLabel4.setText(" GST %");

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });

        lblTotalAmount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotalAmount.setText("Total Amount :");

        lblAMount.setBackground(new java.awt.Color(255, 255, 255));
        lblAMount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAMount.setText("0.0");
        lblAMount.setOpaque(true);

        jLabel5.setText("Rupees");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Discount in Rupees :");

        tfdiscount.setText("0.0");
        tfdiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdiscountActionPerformed(evt);
            }
        });
        tfdiscount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfdiscountKeyReleased(evt);
            }
        });

        jLabel7.setText("Rupees");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Net Amount :");

        lblAMount1.setBackground(new java.awt.Color(255, 255, 255));
        lblAMount1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAMount1.setText("0.0");
        lblAMount1.setOpaque(true);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Rupees");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Customer's Items :");

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));

        jButton3.setText("Delete Item");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));

        jButton4.setText("Create PDF");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel15.setText("DATE : ");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel10))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 57, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblPhoneNo)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tfPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblcustomerdetail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEnterItemName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbladdnewcustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblExtraItem)
                                        .addGap(36, 36, 36)
                                        .addComponent(lblEnterItemName1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jLabel3))
                                    .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2)))))
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTotalAmount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAMount, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(394, 394, 394)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfdiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAMount1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)))
                        .addGap(468, 468, 468)))
                .addComponent(jButton3)
                .addGap(81, 81, 81))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 957, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel15)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblcustomerdetail))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbladdnewcustomer)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEnterItemName)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jButton1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblExtraItem)
                                .addComponent(lblEnterItemName1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhoneNo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAddress)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTotalAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAMount, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfdiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblAMount1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameActionPerformed

    private void tfPhoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPhoneNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPhoneNoActionPerformed

    private void tfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSearchActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void tfSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSearch1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
             if(tfSearch1.getText().trim().isEmpty())
         {
           jLabel13.setText("Enter Item Name");
            tfSearch1.setText("");
            tfSearch1.grabFocus();
            return;
         }
        else if(jTextField2.getText().trim().isEmpty())
         {
            jLabel13.setText("Enter Quantity");
            jTextField2.setText("");
            jTextField2.grabFocus();
            return;
         }
        else if(jTextField3.getText().trim().isEmpty())
         {
            jLabel13.setText("Enter Price per unit");
         
            jTextField3.setText("");
            jTextField3.grabFocus();
            return;
         }
        else if(jTextField4.getText().trim().isEmpty())
        {
              jLabel13.setText("Enter GST in %");
             jTextField4.setText("");
                     jTextField4.grabFocus();
                     return;
        }
        else{
               String quan=jTextField2.getText();
               String pr=jTextField3.getText();
               String gst=jTextField4.getText();
              double pf=Double.parseDouble(pr);
              double q=Double.parseDouble(quan);
               double g=Double.parseDouble(gst);
               double pricew=pf+((pf*g)/100);
                insertintocustomerTable(tfSearch1.getText(),pr,gst,quan,Double.toString(pricew));
                       tfSearch1.setText("");
         jTextField2.setText("");   
             jTextField3.setText("");
        jTextField4.setText("");
              jLabel13.setText("");
        
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tfdiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdiscountActionPerformed

    private void tfSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSearchKeyReleased
           showDataofSearch(tfSearch.getText().trim());        // TODO add your handling code here:
    }//GEN-LAST:event_tfSearchKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                if(tblData.getSelectedRow()==-1)
         {
             JOptionPane.showMessageDialog(NewCustomer.this,"Select a Row to Add...");
             return;
         }
         else if(jTextField1.getText().trim().isEmpty())
          {
            jLabel11.setText("Enter Quantity");
            jTextField1.setText("");
            jTextField1.grabFocus();
              return;
          }
         else{
             jLabel11.setText("");
            DefaultTableModel model=(DefaultTableModel) tblData.getModel();
            int index=tblData.getSelectedRow();
            String name=model.getValueAt(index, 0).toString();
            String price=model.getValueAt(index, 1).toString();
            String gst=model.getValueAt(index, 2).toString();
            String quantity=jTextField1.getText();
            String pricewithgst=model.getValueAt(index, 3).toString();
           // System.out.println("name:"+name+"\n price: "+price+"\ngst: "+gst+"\nquantity : "+quantity+"\n prgst: "+pricewithgst);
            insertintocustomerTable(name,price,gst,quantity,pricewithgst);
            tblData.clearSelection();
         }
        
         
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
            String str = jTextField1.getText();
            //check if int
       //check if float
    try{
        Integer.parseInt(str);
        jLabel11.setText("");
    }catch(NumberFormatException e){
      jTextField1.setText("");        
          jLabel11.setText("Enter only quantity");}
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyReleased

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        tblData1.clearSelection();
        tblData.clearSelection();
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                    if(tblData1.getSelectedRow()==-1)
         {
             JOptionPane.showMessageDialog(NewCustomer.this,"Select a Row to Delete...");
             return;
         }
                    else{
                        
            DefaultTableModel model=(DefaultTableModel) tblData1.getModel();
            int index=tblData1.getSelectedRow();
            String name=model.getValueAt(index, 1).toString();
            String pr=model.getValueAt(index, 6).toString();
               int y=JOptionPane.showConfirmDialog(NewCustomer.this, "Are you sure to Delete item \n"+name,"Delete item "+name, JOptionPane.YES_NO_OPTION); 
                if(y ==0 ){
             
            double p=Double.parseDouble(pr);
           model.removeRow(tblData1.getSelectedRow());
         
           tblData1.clearSelection();
              billPay();
                }
           }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tfdiscountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdiscountKeyReleased
       String str = tfdiscount.getText();
            //check if int
       //check if float
    try{
        Double.parseDouble(str);
        jLabel12.setText("");
    }catch(NumberFormatException e){
      tfdiscount.setText("");        
         jLabel12.setText("Enter only discount"); 
       billPay();
         return;
      }
    billPay();
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdiscountKeyReleased

    private void tfPhoneNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPhoneNoKeyReleased
   
           String str = tfPhoneNo.getText();
    try{
        Long.parseLong(str);
        jLabel14.setText("");
    }catch(NumberFormatException e){
         tfPhoneNo.setText("");        
         jLabel14.setText("Enter only PhonenNumber"); 
      }
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPhoneNoKeyReleased

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
           String str = jTextField2.getText();
    try{
        Integer.parseInt(str);
        jLabel13.setText("");
    }catch(NumberFormatException e){
         jTextField2.setText("");        
         jLabel13.setText("Enter only quantity"); 
      }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
       String str = jTextField3.getText();
    try{
        Double.parseDouble(str);
        jLabel13.setText("");
    }catch(NumberFormatException e){
      jTextField3.setText("");        
         jLabel13.setText("Enter only price"); 
       
      }

        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
       String str = jTextField4.getText();
    try{
        Double.parseDouble(str);
        jLabel13.setText("");
    }catch(NumberFormatException e){
          jTextField4.setText("");        
         jLabel13.setText("Enter only GST %"); 
       
      }
 
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4KeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       String mess="Are you sure to print invoice";
        if(tfName.getText().trim().isEmpty() || tfPhoneNo.getText().trim().isEmpty() || taAddress.getText().trim().isEmpty())
       {
           mess="You didn't provide customer's all details\nAre you sure to print invoice";
         }
        int x=JOptionPane.showConfirmDialog(NewCustomer.this, mess, "Print PDF",JOptionPane.YES_NO_OPTION);
         if(x==0)
         {
               try {
                 String pdfname=jLabel16.getText()+".pdf";
                   printaspdf(pdfname);
                   storecustomerdetailsindatabase(pdfname);
                   
               } catch (DocumentException ex) {
                   Logger.getLogger(NewCustomer.class.getName()).log(Level.SEVERE, null, ex);
               }
         }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed
  public void storecustomerdetailsindatabase(String pdfname)
  {
      
              //set invoice number
       //       jLabel16.getText();
        DBconnect db=new DBconnect();
        com.mysql.jdbc.Connection con=db.connect();
        
        if(con==null)
         {
         // System.out.println("conn not estabish");
           JOptionPane.showMessageDialog(NewCustomer.this,"Data Base Connection Failed \n");
          //this.setVisible(false);
          this.dispose();
         }
        String query = "INSERT INTO `customer`(`cname`, `phone`, `address`, `pdfname`) VALUES (?,?,?,?)";
        try {

             PreparedStatement pst=null;
               PreparedStatement preparedStmt = con.prepareStatement(query);
              //preparedStmt.setInt (1, 112);
              preparedStmt.setString (1, tfName.getText());
              preparedStmt.setString (2, tfPhoneNo.getText());
              preparedStmt.setString (3, taAddress.getText());
              preparedStmt.setString (4, pdfname);              
              preparedStmt.execute();
        
             con.close();
            }
         catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        
        
  }

    public void insertintocustomerTable(String name,String price,String gst,String quantity,String pricewithgst)
 {
 
          int quan=Integer.parseInt(quantity);
          double ppunit=Double.parseDouble(price);
          double pricewgst=Double.parseDouble(pricewithgst);
          double tprice=quan*ppunit;
          double netprice=pricewgst*quan;
         
          //String tp=Float.toString(tprice);
          //String nt=Float.toHexString(netprice);
    DefaultTableModel model=model=(DefaultTableModel)tblData1.getModel();
    
    model.insertRow(tblData1.getRowCount(),new Object[]{
                      flag,
                      name,
                      price,
                      quantity,
                      df.format(tprice),
                      gst,
                      df.format(netprice)                      
                  });
           jLabel11.setText("");
           billPay();
 }

 public void billPay()
 {
     double amount=0;
     int rows = tblData1.getRowCount();
      DefaultTableModel model=(DefaultTableModel) tblData1.getModel();
            totalamount=0;
            for(int i=0;i<rows;i++)
            {
                String name=model.getValueAt(i, 6).toString();  
                amount=Double.parseDouble(name);
                totalamount+=amount;
               //model.addRow(new Object[]{i});
                model.setValueAt(i+1, i, 0);
            }
              
//     totalamount+=amount;
     if(tfdiscount.getText().isEmpty())
     {
     discount=0.0;
     }
     else{
     discount=Double.parseDouble(tfdiscount.getText());
     }     
     netamount=totalamount-discount;
//     
     lblAMount.setText(String.valueOf(df.format(totalamount)));
     lblAMount1.setText(String.valueOf(df.format(netamount)));
 }
    
public void showdatetime()
{
         DBconnect DBcon=new DBconnect(); 
         Connection conn=DBcon.connect();
         if(conn==null)
         {
          System.out.println("conn not estabish");
          JOptionPane.showMessageDialog(NewCustomer.this,"Data Base Connection Failed \n");
          //this.setVisible(false);
          this.dispose();
         }
    
        Date date=new Date();
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy  HH~mm~ss");
        //System.out.println(formatter.format(date));
        jLabel16.setText(formatter.format(date).toString());
        //set invoice number
        
         long numberRow=0;
         String query2 = "select count(*) from customer";
        try {
            PreparedStatement st = conn.prepareStatement(query2);
            ResultSet rs = st.executeQuery();
            while(rs.next()){
            numberRow = rs.getInt("count(*)");
             
            }
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        numberRow++;
        jLabel17.setText(String.valueOf(numberRow));
    
}

 public void showData()
       {
         DBconnect DBcon=new DBconnect(); 
         Connection conn=DBcon.connect();
         if(conn==null)
         {
          System.out.println("conn not estabish");
          JOptionPane.showMessageDialog(NewCustomer.this,"Data Base Connection Failed \n");
          //this.setVisible(false);
          this.dispose();
         }
         String query="SELECT * FROM items";
        try {
           
            PreparedStatement stm=conn.prepareStatement(query);
            ResultSet rs=stm.executeQuery();
            DefaultTableModel tm=(DefaultTableModel) tblData.getModel();
            tm.setRowCount(0);
             while(rs.next())
             {
                String item=rs.getString("itemname");
                String p=rs.getString("price");
                String g=rs.getString("GST");
                double pf=Double.parseDouble(p);
                double gf=Double.parseDouble(g);
                double to=pf+((pf*gf)/100);
               // String t=Float.toString(to);
                tm.addRow(new Object[]{item,p,g,df.format(to)});
             }
            
            //tblData.setModel(DbUtils.resultSetToTableModel(rs)); 
            conn.close();
        } catch (SQLException ex) {
            System.out.println("query not prepare");
        }
    }
       public void showDataofSearch(String name)
    {
         DBconnect DBcon=new DBconnect();  
         Connection conn=DBcon.connect();
        if(conn==null)
         {
         // System.out.println("conn not estabish");
           JOptionPane.showMessageDialog(NewCustomer.this,"Data Base Connection Failed \n");
          //this.setVisible(false);
          this.dispose();
         }
        
        try {
         String query="SELECT * FROM items where itemname like ?";   
            PreparedStatement stm=conn.prepareStatement(query);
            stm.setString(1, name+"%");
            ResultSet rs=stm.executeQuery();
            DefaultTableModel tm=(DefaultTableModel) tblData.getModel();
            
            tm.setRowCount(0);
             while(rs.next())
             {
                String item=rs.getString("itemname");
                String p=rs.getString("price");
                String g=rs.getString("GST");
               double pf=Double.parseDouble(p);
               double gf=Double.parseDouble(g);
               double to=pf+((pf*gf)/100);
                //String t=Float.toString(to);
                tm.addRow(new Object[]{item,p,g,df.format(to)});
             }
            
                conn.close();   
        } catch (SQLException ex) {
            System.out.println("query not prepare");
        }

    }
    
       public void printaspdf(String pdfname) throws DocumentException
       {
            Information info=new Information();
           Document document=new Document(PageSize.LETTER.rotate());
           
        try {
        
            PdfWriter.getInstance(document ,new FileOutputStream(info.getinfo(6)+""+pdfname));
            
        
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NewCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
           
           document.open();
           Font f1=new Font(Font.FontFamily.TIMES_ROMAN,20,Font.BOLD,BaseColor.RED);
           
           Paragraph p1=new Paragraph("                                                         INVOICE               ",f1 );
           Font f2=new Font(Font.FontFamily.TIMES_ROMAN,15,Font.NORMAL,BaseColor.RED);
           Font fin=new Font(Font.FontFamily.UNDEFINED,15,Font.NORMAL,BaseColor.BLACK);
           Paragraph invoice=new Paragraph("                                                                                                                                          S.No: "+jLabel17.getText(),fin);
           Paragraph p2=new Paragraph(info.getinfo(3)+"                                                                       Date : "+jLabel16.getText(),f2 );
           Font f3=new Font(Font.FontFamily.UNDEFINED,12,Font.NORMAL,BaseColor.BLUE);
           Paragraph p3=new Paragraph("Phone No: "+info.getinfo(4),f3 );
           Font f4=new Font(Font.FontFamily.UNDEFINED,12,Font.UNDERLINE,BaseColor.BLUE);
           Paragraph p4=new Paragraph("Email ID: "+info.getinfo(5)+"                                                                                                                                              ",f4 );
            //+jLabel17.getText()
           Font f5=new Font(Font.FontFamily.COURIER,13,Font.UNDERLINE,BaseColor.RED);                 
           Paragraph p5=new Paragraph("Customer Details :-",f5);
           Paragraph p6=new Paragraph("Name : "+tfName.getText());
           Paragraph p7=new Paragraph("Phone No: "+tfPhoneNo.getText());
                    //  Font f5=new Font(Font.FontFamily.UNDEFINED,12,Font.UNDERLINE);
           Paragraph p8=new Paragraph("Address: "+taAddress.getText()+"\n");
           document.add(p1);
           document.add(invoice);
           document.add(p2);
           document.add(p3);
           document.add(p4);
           document.add(p5);
           document.add(p6);
           document.add(p7);
           document.add(p8);
        
               PdfPTable pdfTable = new PdfPTable(tblData1.getColumnCount());
               
               for (int i = 0; i < tblData1.getColumnCount(); i++) {
                pdfTable.addCell(tblData1.getColumnName(i));
            }

                for (int rows = 0; rows < tblData1.getRowCount() ; rows++) {
                for (int cols = 0; cols < tblData1.getColumnCount(); cols++) {
                    pdfTable.addCell(tblData1.getModel().getValueAt(rows, cols).toString());

                }
            }
                               float[] columnWidths = new float[]{10f, 30f, 20f, 10f,20f,10f,25f};
               pdfTable.setWidths(columnWidths); 
              document.add(pdfTable);
//                double tam=Double.parseDouble(lblAMount.getText());
//                double dis=Double.parseDouble(tfdiscount.getText());
//                double net=Double.parseDouble(lblAMount1.getText());
               Font f10=new Font(Font.FontFamily.TIMES_ROMAN,15,Font.NORMAL,BaseColor.BLACK);       
               Paragraph p10=new Paragraph("\nTotal Amount =    "+lblAMount.getText()+"  Rupees",f10);
               Paragraph p11=new Paragraph("Discount =        "+tfdiscount.getText()+"  Rupees",f10);
               
               Font f12=new Font(Font.FontFamily.TIMES_ROMAN,15,Font.NORMAL,BaseColor.RED);
               Paragraph p12=new Paragraph("Net Amount =      "+lblAMount1.getText()+"   Rupees",f12);
              document.add(p10);
              document.add(p11);
              document.add(p12);
              document.close();
           
            
       }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new NewCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lblAMount;
    private javax.swing.JLabel lblAMount1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblEnterItemName;
    private javax.swing.JLabel lblEnterItemName1;
    private javax.swing.JLabel lblExtraItem;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhoneNo;
    private javax.swing.JLabel lblTotalAmount;
    private javax.swing.JLabel lbladdnewcustomer;
    private javax.swing.JLabel lblcustomerdetail;
    private javax.swing.JTextArea taAddress;
    private javax.swing.JTable tblData;
    private javax.swing.JTable tblData1;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfPhoneNo;
    private javax.swing.JTextField tfSearch;
    private javax.swing.JTextField tfSearch1;
    private javax.swing.JTextField tfdiscount;
    // End of variables declaration//GEN-END:variables
}
